"""Markdown report generation for discovered papers."""

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from research_desk.config import ARXIV_MIN_PAPER_YEAR, DOWNLOADS_DIR


def normalize_whitespace(value: str) -> str:
    """Collapse repeated whitespace for readable Markdown output."""

    return " ".join(value.split())


def slugify_filename(value: str) -> str:
    """Create a short, filesystem-safe slug for a report filename."""

    slug = re.sub(r"[^a-z0-9]+", "-", value.casefold()).strip("-")
    return slug[:70] or "research-idea"


def build_arxiv_report_markdown(
    idea: dict[str, Any],
    papers: list[dict[str, Any]],
    generated_at: datetime | None = None,
) -> str:
    """Build a polished Markdown report from an idea and arXiv results."""

    report_time = generated_at or datetime.now(timezone.utc)
    title = normalize_whitespace(str(idea.get("title", "Untitled Research Idea")))
    problem = normalize_whitespace(str(idea.get("problem", "Not provided.")))
    tags = [normalize_whitespace(str(tag)) for tag in idea.get("tags", [])]
    tags = [tag for tag in tags if tag]

    lines = [
        f"# {title}",
        "",
        "## Research Idea",
        "",
        f"- **Idea ID:** {idea.get('id', 'N/A')}",
        f"- **Priority:** {idea.get('priority', 'N/A')}",
        f"- **Status:** {idea.get('status', 'N/A')}",
        f"- **Tags:** {', '.join(tags) if tags else 'None'}",
        f"- **Report generated:** {report_time.strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Research Problem",
        "",
        problem,
        "",
        "## Literature Scope",
        "",
        (
            f"This report contains {len(papers)} arXiv paper(s) originally "
            f"published in {ARXIV_MIN_PAPER_YEAR} or later."
        ),
        "",
        "## Papers",
        "",
    ]

    if not papers:
        lines.extend(["No matching papers were found for this research idea.", ""])

    for index, paper in enumerate(papers, start=1):
        authors = paper.get("authors", [])
        categories = paper.get("categories", [])
        author_text = ", ".join(authors) if authors else "Not listed"
        category_text = ", ".join(categories) if categories else "Not listed"
        summary = normalize_whitespace(str(paper.get("summary", "")))

        lines.extend(
            [
                f"### {index}. {paper.get('title', 'Untitled Paper')}",
                "",
                f"- **Authors:** {author_text}",
                f"- **Published:** {paper.get('published', 'Unknown')}",
                f"- **Updated:** {paper.get('updated', 'Unknown')}",
                f"- **Primary category:** "
                f"{paper.get('primary_category') or 'Not listed'}",
                f"- **Categories:** {category_text}",
                f"- **arXiv ID:** {paper.get('arxiv_id', 'Unknown')}",
                "",
                "**Abstract**",
                "",
                summary or "No abstract was provided.",
                "",
                f"[View on arXiv]({paper.get('arxiv_url', '')}) | "
                f"[Download PDF]({paper.get('pdf_url', '')})",
                "",
                "---",
                "",
            ]
        )

    lines.extend(
        [
            "*Generated by Research Desk MCP.*",
            "",
            "Thank you to arXiv for use of its open-access interoperability.",
            "",
        ]
    )
    return "\n".join(lines)


def write_arxiv_report(
    idea: dict[str, Any],
    papers: list[dict[str, Any]],
    output_dir: Path | None = None,
    generated_at: datetime | None = None,
) -> Path:
    """Write a uniquely named Markdown report to Downloads."""

    report_time = generated_at or datetime.now(timezone.utc)
    destination = output_dir or DOWNLOADS_DIR
    destination.mkdir(parents=True, exist_ok=True)

    idea_id = int(idea["id"])
    title_slug = slugify_filename(str(idea.get("title", "")))
    timestamp = report_time.strftime("%Y%m%d-%H%M%S")
    base_name = f"research-desk-idea-{idea_id:03d}-{title_slug}-{timestamp}"
    report_path = destination / f"{base_name}.md"
    duplicate_number = 2

    while report_path.exists():
        report_path = destination / f"{base_name}-{duplicate_number}.md"
        duplicate_number += 1

    report_path.write_text(
        build_arxiv_report_markdown(idea, papers, report_time),
        encoding="utf-8",
    )
    return report_path
